#BNF+EMV2.0;
!grammar experiencecenter_fr;
!start <idleleg>;
!start <questiongreeting>;
!start <questionshy>;
!start <questionability>;
!start <questiondance>;
!start <questionlaguage>;
!start <questionvibe>;
!start <questionpresence>;
!start <questionpresentation>;
!start <idlesee>;
!start <byecome>;
!start <movego>;
<idleleg> : [as-tu envie de te] (dégourdi [toi] | dégourdir) (tes | vos | les) jambes ;
<questiongreeting> : (comment [tu vas | vas-tu | ça va] | ça va) [Buddy];
<questionshy> : [Buddy] (([es-tu |  tu es] timide) | ([as-tu | tu as] perdu ta langue));
<questionability> : [que | qu'est ce que] (sais-tu | tu sais | tu peux | peux-tu) faire [quoi] [pour nous] | dis nous ce que tu sais faire ;
<questiondance> : [peux-tu | sais-tu | tu sais | tu peux] danser;
<questionlaguage> : tu parles (quelle langue | combien de langues) | quelle langue (tu parles | parles-tu);
<questionvibe> : ((peux-tu [gérer | mettre de]) | mets de) l'ambiance | sais-tu créer une ambiance;
<questionpresence> : (es-tu | que fais-tu | [pourquoi] (tu es | es-tu)) (là | ici) [aujourd'hui];
<questionpresentation> : parle [moi | nous] de toi | présente toi | peux-tu nous parler de toi;
<idlesee> : (ravi | content) de te revoir | c'est super de te voir;
<byecome> : viens ([par] (ici | là) | dans mes bras);
<movego>  : vas y | tu peux y aller;




