#BNF+EMV2.0;
!grammar experiencecenter_en;
!start <idleleg>;
!start <questiongreeting>;
!start <questionshy>;
!start <questionability>;
!start <questiondance>;
!start <questionlaguage>;
!start <questionvibe>;
!start <questionpresence>;
!start <questionpresentation>;
!start <idlesee>;
!start <byecome>;
!start <movego>;
<idleleg> : [do you want to stretch] your (leg | legs);
<questiongreeting> : (how are (you [doing] | doing) | how's it going) [Buddy];
<questionshy> : [Buddy] (you are shy | cat got your tongue);
<questionability> : what [can | could] you do [for us];
<questiondance> : can you dance;
<questionlaguage> : (which | what | how many) language [do you (speak | spoke)];
<questionvibe> : can you create an ambiance | vibe;
<questionpresence> : (why | what) are you (here | doing here) [today];
<questionpresentation> : tell us about you | (introduce | present) yourself | explain who you are | who are you;
<idlesee> : nice to (see | meet) you;
<byecome> : come into my (arms | arm) | come here;
<movego>  : you can go;




