#BNF+EMV2.1;
!grammar commands_fr;
!start <repeat>;
!start <quit>;
!start <first>;
!start <second>;
!start <third>;
<repeat> : ([est-ce que] je peux | peut-on | peux-tu | [est-ce qu'] on peut | tu peux) répéter | répète;
<quit> : quitter | arreter | sortir | terminer | quitte | ferme | arrete | arret| fin;
<first> : premier | la premiere | la premiere | la réponse un;
<second> : deuxieme | la deuxieme | second | la réponse deux;
<third> : (la) troisieme | troisieme | la réponse trois;