#BNF+EMV2.1;
!grammar number_player_fr;
!start <answer>;
!start <quit>;
!import <numbers#nb>;
<answer> : [Il y a | Il y en a] <numbers#nb>;
<quit> : quitter | annuler | arrêter | sortir | terminer | annule | quitte | ferme | arrête | arrêt | ce sera tout | rien | fin;