#BNF+EMV2.1;
!grammar app_grammar_nl;
!start <yes>;
!start <no>;
!start <quit>;
!start <play>;
!start <parameters>;
!start <didntunderstand>;
<yes> : ja | Oke | is goed | jazeker | prima | doen we;
<no> : Nee | Nee hoor | neh | niet | zeker niet | nee oneens;
<quit> : Stop | hou op | stop daarmee;
<play> : jouer;
<parameters> : paramètres | paramètrer | configurer | configuration;
<didntunderstand> : [je n'ai pas [bien] (compris | entendu)] peux tu (répéter | reformuler);