#BNF+EMV2.1;
!grammar app_grammar_en;
!start <date>;
!start <hour>;
!start <calcul>;
<date> : what (day | date) are we | [what is | give me] the date;
<hour> : what time is it | give [me | us] the time | what is the time;
<calcul> : [(what | how much) is] (three times six | six times three);