#BNF+EMV2.1;
!grammar app_grammar_fr;
!start <date>;
!start <hour>;
!start <calcul>;
<askgive> : (<canyou> [me | nous] (donner | dire)) | ((donne | dis) [moi | nous]) | (je (veux | voudrais) que tu [me | nous] (donnes | dises));
<canyou> : (peux-tu | pourrais-tu | [est-ce que] tu (peux | pourrais));
<date> :  quel jour sommes nous | <askgive> la date | quelle est la date | quel jour on est | quel jour est-on | on est quel jour;
<hour> :  quelle heure est-il | <askgive> l'heure | il est quelle heure | c'est quoi l'heure;
<calcul> : [combien (font|fait)] (trois fois six | six fois trois);
