#BNF+EMV2.1;
!grammar weather_fr;
!start <weather>;
!import <cities#name>;
<weather> : (<request1> | <request2> | <request3> | <request4> | <request5>) [à <cities#name> [<when>] | <when> [à <cities#name>]] [s'il te plait];
<request1> : (<subrequest11> | <subrequest12>) (la température | (la | les prévisions) météo | le temps);
<subrequest11> : (peux-tu | pourrais-tu | [est-ce que] tu (peux | pourrais)) [me | nous] (donner | dire);
<subrequest12> : quel (est | sera);
<request2> : ([quand] (va-t-il | est-ce qu'il va))( pleuvoir | neiger | geler );
<request3> : ([quand] (fera-t-il | fait-il) | est-ce qu'il (fait | fera)) (beau | pluvieux | chaud | froid | brumeux | nuageux );
<request4> :  ([quand] (y aura-t-il | y a-t-il) | est-ce qu'il (a | aura))(du soleil | de la pluie | de la neige | du vent  | du brouillard | des nuages | de l'orage | une tempête);
<request5> : quel temps (fait-il | quel temps fera-t-il);
<date> : (aujourd'hui | demain);
<partofday> : (matin | midi | soir);
<when> : (<dayoftheweek> | <date>) [[le] <partofday>] | (ce | le prochain) weekend | le weekend prochain | ce <partofday> | cette semaine;
<dayoftheweek> : Lundi | Mardi | Mercredi | Jeudi | Vendredi | Samedi | Dimanche;
