#BNF+EMV2.0;
!grammar reminder_date_en;
!import <numbers#nb>;
!start <today>;
!start <tomorrow>;
!start <dayaftertomorrow>;
!start <nextdayofweek>;
!start <nextweek>;
!start <nextmonth>;
!start <nextyear>;
!start <nextday>;
!start <nextdate>;
!start <fulldate>;
!start <indays>;
!start <inweeks>;
!start <inmonths>;
!start <inyears>;
<today> : today;
<tomorrow> : tomorrow;
<dayaftertomorrow> : ([the] day after tomorrow);
<nextdayofweek> : [next | on] <dayofweek>;
<nextweek> : next week;
<nextmonth> : next month;
<nextyear> : next year;
<nextday> : the <dayofmonth>;
<nextdate> : [the] <dayofmonth> [of] <month> | [on] <month> <dayofmonth>;
<fulldate> : <nextdate> <year>;
<indays> : in <numbers#nb> day[s];
<inweeks> : in <numbers#nb> week[s];
<inmonths> : in <numbers#nb> month[s];
<inyears> : in <numbers#nb> (year[s]);
<dayofweek> : (Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday);
<dayofmonth> : first | second | third | fourth | fifth | sixth | seventh | eighth | ninth | tenth | eleventh | twelfth | thirteenth | fourteenth | fifteenth | sixteenth | seventeenth | eighteenth | nineteenth | twentieth | twenty-first | twenty-second | twenty-third | twenty-fourth | twenty-fifth | twenty-sixth | twenty-seventh | twenty-eighth | twenty-ninth | thirty | thirty-first;
<month> : january | february | march | april | may | june | july | august | september | october | november | december;
<year> : <numbers#nb> | <subyear><subyear>;
<subyear> : 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 76 | 77 | 78 | 79 | 80 | 81 | 82 | 83 | 84 | 85 | 86 | 87 | 88 | 89 | 90 | 91 | 92 | 93 | 94 | 95 | 96 | 97 | 98 | 99 | 100;