#BNF+EMV2.0;
!grammar reminder_fr;
!start <recurrenceweek>;
!start <recurrencemonth>;
!start <recurrenceday>;
!start <everybody>;
!start <modify>;
<recurrenceweek> : toutes les semaines;
<recurrencemonth> : tous les mois;
<recurrenceday> : tous les jours ;
<everybody> : tout le monde | personne ;
<modify> : modifier;