#BNF+EMV2.0;
!grammar reminder_date_en;
!import <numbers#nb>;
!start <day>;
!start <indate>;
<day> : today | tomorrow | day after tomorrow | (monday | tuesday | wednesday | thursday | friday | saturday | sunday) [next | <numbers#nb> [<month>]] | the <numbers#nb> [<month>];
<month> : january | february | march | april | may | june | july | august | september | october | november | december;
<indate> : in <numbers#nb> (day[s] | month[s] | year[s]);