#BNF+EMV2.0;
!grammar reminder_en;
!start <recurrenceweek>;
!start <recurrencemonth>;
!start <recurrenceday>;
!start <everybody>;
!start <modify>;
<recurrenceweek> : every week;
<recurrencemonth> : every month;
<recurrenceday> : every day;
<everybody> : everyone | nobody;
<modify> : modify;