#BNF+EMV2.0;
!grammar duration_en;
!import <numbers#nb>;

!export <duration_years>;
!export <duration_months>;
!export <duration_weeks>;
!export <duration_days>;
!export <duration_hours>;
!export <duration_minutes>;
!export <duration_hoursandminutes>;

<duration_years> : <numbers#nb> year[s];
<duration_months> : <numbers#nb> month[s];
<duration_weeks> : <numbers#nb> week[s];
<duration_days> : <numbers#nb> day[s];
<duration_hours> : <numbers#nb> hour[s];
<duration_minutes> : <numbers#nb> minute[s];
<duration_hoursandminutes> : <duration_hours> [and] <numbers#nb> [minute[s]];