#BNF+EMV2.0;
!grammar gallery_nl;
!start <delete>;
!start <next>;
!start <previous>;
!start <share>;
<delete>: (verwijder [de | deze] [foto]) | [haal | [o] doe] [de | deze] foto [maar | kan] weg | [[o] doe] [maar] weg [ermee] | verwijderen; 
<next>: (volgende | andere) [foto]; 
<previous>:  (vorige | eerste | eerdere)  [foto];
<share>: delen | publiceren | (deer | publiceer) [maar]; 