#BNF+EMV2.1;
!grammar companion_questions_fr;
!start <qhello>;
!start <qhappy>;
!start <qwtcanyoudo>;
!start <qwhoareyou>;
!start <qname>;
!start <qchangename>;
!start <qhowareyou>;
!start <qcook>;
!start <qhoover>;
!start <qcoffee>;
!start <qlanguage>;
!start <qeat>;
!start <qage>;
!start <qfather>;
!start <qparents>;
!start <qwhomadeyou>;
!start <qgender>;
!start <qrobot>;
!start <qmimicdog>;
!start <qmimiccat>;
!start <qsiblings>;
!start <qkissyou>;
!start <qknowroboticrules>;
!start <qroboticrules>;
!start <qfavoritecolor>;
!start <qfavoritemusic>;
!start <qfavoriteactor>;
!start <qfavoriteactress>;
!start <qfavoritemovie>;
!start <qfavoritegame>;
!start <qheight>;
!start <qweight>;
!start <qsize>;
!start <qautonomy>;
!start <qchargingtime>;
!start <qchargingmod>;
!start <qfineandyou>;
!start <qgoodafternoon>;
!start <qgoodevening>;
!start <qgoodnight>;
!start <qgoodday>;
!start <qgoodbye>;
!start <qwhoisobama>;
!start <qwhoismbouygues>;

<qhello> : bonjour [buddy];
<qhappy> : ([est-ce que] (tu es | t'es) | es-tu) (content | heureux) [d'être (avec nous | là)];
<qwtcanyoudo> : que sais-tu faire  | (dis (moi | nous) | (pourrais-tu | peux-tu | tu peux | tu pourrais) [m' | nous] expliquer) ce que tu sais faire. | qu'est-ce que tu sais faire | tu sais faire quoi;
<qwhoareyou> : t'es qui | qui es-tu;
<qname> : comment ( t'appelles tu | tu t'appelles) | (c'est quoi | quel est) ton [petit] nom;
<qchangename> : ([est-ce que] je peux | peut-on | [est-ce qu'] on peut) changer ton (nom | prénom);
<qhowareyou> : comment (vas-tu | ça va | tu vas) | ça va | tu vas bien;
<qcook> : (sais-tu | [est-ce que] tu sais) (cuisiner | faire à manger) | [est-ce que] tu cuisines | cuisines-tu;
<qhoover> : ([est-ce que] tu (passes | sais passer) | passes-tu ) l'aspirateur;
<qcoffee> : [est-ce que] tu fais le café | sais-tu faire le café | fais-moi un café;
<qlanguage> : quelle langue parles-tu | tu parles quelle langue ;
<qeat> : que manges-tu  | as-tu faim  | veux-tu à manger;
<qage> : quel âge as-tu | (quand | quel jour | en quelle année) es-tu né | c'est quand ton anniversaire | tu es né quand;
<qfather> : (qui est | c'est qui | il est où) ton père;
<qparents> : (qui sont tes | as-tu des) parents | quelles sont tes origines;
<qwhomadeyou> : qui t'a (conçu | fabriqué);
<qgender> : es-tu (un homme | un garçon | une femme | une fille);
<qrobot> : (es-tu | tu es | t'es) un robot [alors];
<qmimicdog> : imite le chien;
<qmimiccat> : imite le chat;
<qsiblings> : as-tu des frères et soeurs;
<qkissyou> : je peux te faire un bisou | est-ce que je peux t'embrasser;
<qknowroboticrules> : les robots répondent à quelles règles | ([est-ce que] tu (respectes | connais) | connais-tu | qui a inventé) les (lois | règles) (de la robotique | des robots);
<qroboticrules> : quelles sont les (lois | règles) de la robotique | les robots répondent à quelle loi;
<qfavoritecolor> : quelle est ta couleur préférée;
<qfavoritemusic> : quelle est ta musique préférée;
<qfavoriteactor> : quel est ton acteur préféré;
<qfavoriteactress> : quelle est ton actrice préférée;
<qfavoritemovie> : quel est ton film préféré ;
<qfavoritegame> : quel est ton jeu préféré ;
<qheight> : tu mesures combien | combien mesures-tu | quelle taille fais-tu | quelle est ta taille;
<qweight> : tu pèses combien | combien pèses-tu | quel poids fais-tu | quel est ton poids;
<qsize> : quelles sont tes dimensions;
<qautonomy> : quelle est ton autonomie | combien de temps dure ta batterie | quelle est la durée de ta batterie | combien de temps ta batterie dure;
<qchargingtime> : combien de temps tu mets pour te charger | quel est ton temps de charge | en combien de temps tu te charges | combien de temps il te faut pour te recharger;
<qchargingmod> : comment te (recharges-tu | charges-tu) | [est-ce que] tu sais te recharger;
<qfineandyou> : [ça va | je vais] (bien | pas mal) [merci] [et toi [comment ça va]];
<qgoodafternoon> : bon après-midi;
<qgoodevening> : bonsoir | bonne soirée;
<qgoodnight> : bonne nuit;
<qgoodday> : bonne journée;
<qgoodbye> : au revoir | à bientôt;
<qwhoisobama> : qui est Barack Obama;
<qwhoismbouygues> : qui est Martin Bouygues;