#BNF+EMV2.1;
!grammar weather_en;
!start <weather>;
!import <cities#name>;
<weather> : ((<request1> | <request2> | <request3> | <request4>) ([in <cities#name> [<when>] | <when> [in <cities#name>]])) [please] ;
<request1> : (<subrequest11> | <subrequest12>) the (temperature | weather | forecast) [like];
<subrequest11> : [can you] (give | tell) [me | us];
<subrequest12> : (what will be | what is | what's);
<request2> : ([when] will it | [when] is it going to | does it)( rain | snow | freeze );
<request3> : ([when] will it be | is it) (sunny | rainy | raining | snowy | snowing | frozen | windy | hot | cold | foggy | cloudy );
<request4> :  ([when] will there be | is there)(sun | rain | snow | wind  | fog | cloud | thunder | lightening);
<date> : (tomorrow | today);
<partofday> : morning | afternoon | evening | at noon;
<when> : (<dayoftheweek> | <date>) [[the] <partofday>] | (this | next) weekend | this <partofday> | this week;
<dayoftheweek> : Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday;
