#BNF+EMV2.1;
!grammar common_nl;
!start <yes>;
!start <no>;
!start <quit>;
!start <didntunderstand>;
<yes> : ja [ja | hoor | snap ik | [dat | da] klopt] | o ja [hoor] | [goed | heel | [dat] is | das | oke] goed | yep | yeah | tuurlijk | inderdaad | zeker | [das] prima | [das] oke | [Ik] [ben het ermee] eens | eens hoor | begrijp [het | ik] | dat begrijp ik | [Ik [heb het]] begrepen | [dat | da] doen we | sure | [dat | da] klopt [ja] | Ik begrijp [het] | [ik] snap het | [dat | da] snap ik;
<no> : o nee [hoor | joh] | nee [joh | nee | hoor | niet | helemaal niet | nooit | denk het niet | liever niet | joh] | no | oneens | stop | niet doen | [wil [ik] | hoeft | hoef ik | liever | o helemaal | dat denk ik | da denk ik | denk het | denk ik] niet | [o] nooit;
<quit> : het is genoeg | genoeg | genoeg geweest | het is mooi geweest | stop | stoppen | verlaat | verlaten | annuleer | annuleren | exit | niks | niets | terug | trug | einde | eind | weg;
<didntunderstand> : [Ik (begrijp | begreep) het niet] (kan je | zou je het kunnen) herhalen;
