#BNF+EMV2.1;
!grammar companion_questions_fr;
!start <qhello>;
!start <qhappy>;
!start <qwtcanyoudo>;
!start <qwhoareyou>;
!start <qname>;
!start <qchangename>;
!start <qhowareyou>;
!start <qcook>;
!start <qhoover>;
!start <qcoffee>;
!start <qlanguage>;
!start <qeat>;
!start <qage>;
!start <qfather>;
!start <qparents>;
!start <qwhomadeyou>;
!start <qgender>;
!start <qrobot>;
!start <qmimicdog>;
!start <qmimiccat>;
!start <qsiblings>;
!start <qkissyou>;
!start <qknowroboticrules>;
!start <qroboticrules>;
!start <qfavoritecolor>;
!start <qfavoritemusic>;
!start <qfavoriteactor>;
!start <qfavoriteactress>;
!start <qfavoritemovie>;
!start <qfavoritegame>;
!start <qheight>;
!start <qweight>;
!start <qsize>;
!start <qautonomy>;
!start <qchargingtime>;
!start <qchargingmod>;
!start <qfineandyou>;
!start <qgoodafternoon>;
!start <qgoodevening>;
!start <qgoodnight>;
!start <qgoodday>;
!start <qgoodbye>;
!start <qweathernice>;
!start <qhowarefriends>;
!start <qnotwell>;
!start <qvisit>;
!start <qsleepwell>;
!start <qpain>;
!start <qweathernotnice>;
!start <qsickfriend>;
!start <qsunnyday>;
!start <qrainyday>;
!start <qmissfamily>;
!start <qfeelalone>;
!start <qwhattodo>;
!start <qgrumpyfriend>;
!start <qcontest>;
!start <qgoingtocook>;
!start <qloosingmemory>;
!start <qforgetmedecine>;
!start <qsawsomeone>;
!start <qhadawalk>;
!start <qaremedoctaken>;
!start <qhereissone>;
!start <qlostglasses>;
!start <qloststhing>;
!start <qdentistappointment>;
!start <qmedicalappointmenteye>;
!start <qfell>;
!start <qmedicalappointment>;
!start <qsomeonedied>;
!start <qmybirthday>;
!start <qplaygame>;
!start <qactivity>;
!start <qlostgame>;
!start <qcanplaymusic>;
!start <qfavoritebook>;
!start <qwhatisontv>;
!start <qdanceshow>;
!start <qstory>;
!start <qlike>;
!start <qcookwithtomatoe>;
!start <qsharefood>;
!start <qseathesee>;
!start <qtravel>;
!start <qokaybuddy>;
!start <qokaygoogle>;
!start <qheyalexa>;

!start <qthankyou>;

<qhello> : (bonjour | salut) [buddy];
<qhappy> : ([est-ce que] (tu es | t'es) | es-tu) (content | heureux) [d'être (avec nous | là)];
<qwtcanyoudo> : que sais-tu faire  | (dis (moi | nous) | (pourrais-tu | peux-tu | tu peux | tu pourrais) [m' | nous] expliquer) ce que tu sais faire. | qu'est-ce que tu sais faire | tu sais faire quoi;
<qwhoareyou> : t'es qui | qui es-tu;
<qname> : comment ( t'appelles tu | tu t'appelles) | (c'est quoi | quel est) ton [petit] nom;
<qchangename> : ([est-ce que] je peux | peut-on | [est-ce qu'] on peut) changer ton (nom | prénom);
<qhowareyou> : comment (vas-tu | ça va | tu vas) | ça va | tu vas bien;
<qcook> : (sais-tu | [est-ce que] tu sais) (cuisiner | faire à manger) | [est-ce que] tu cuisines | cuisines-tu;
<qhoover> : ([est-ce que] tu (passes | sais passer) | passes-tu ) l'aspirateur;
<qcoffee> : [est-ce que] tu fais le café | sais-tu faire le café | fais-moi un café;
<qlanguage> : quelle langue parles-tu | tu parles quelle langue ;
<qeat> : que manges-tu  | as-tu faim  | veux-tu à manger;
<qage> : quel âge as-tu | (quand | quel jour | en quelle année) es-tu né | c'est quand ton anniversaire | tu es né quand;
<qfather> : (qui est | c'est qui | il est où) ton père;
<qparents> : (qui sont tes | as-tu des) parents | quelles sont tes origines;
<qwhomadeyou> : qui t'a (conçu | fabriqué);
<qgender> : es-tu (un homme | un garçon | une femme | une fille);
<qrobot> : (es-tu | tu es | t'es) un robot [alors];
<qmimicdog> : imite le chien;
<qmimiccat> : imite le chat;
<qsiblings> : as-tu des frères et soeurs;
<qkissyou> : je peux te faire un bisou | est-ce que je peux t'embrasser;
<qknowroboticrules> : les robots répondent à quelles règles | ([est-ce que] tu (respectes | connais) | connais-tu | qui a inventé) les (lois | règles) (de la robotique | des robots);
<qroboticrules> : quelles sont les (lois | règles) de la robotique | les robots répondent à quelle loi;
<qfavoritecolor> : quelle est ta couleur préférée;
<qfavoritemusic> : quelle est ta musique préférée;
<qfavoriteactor> : quel est ton acteur préféré;
<qfavoriteactress> : quelle est ton actrice préférée;
<qfavoritemovie> : quel est ton film préféré ;
<qfavoritegame> : quel est ton jeu préféré ;
<qheight> : tu mesures combien | combien mesures-tu | quelle taille fais-tu | quelle est ta taille;
<qweight> : tu pèses combien | combien pèses-tu | quel poids fais-tu | quel est ton poids;
<qsize> : quelles sont tes dimensions;
<qautonomy> : quelle est ton autonomie | combien de temps dure ta batterie | quelle est la durée de ta batterie | combien de temps ta batterie dure;
<qchargingtime> : combien de temps tu mets pour te charger | quel est ton temps de charge | en combien de temps tu te charges | combien de temps il te faut pour te recharger;
<qchargingmod> : comment te (recharges-tu | charges-tu) | [est-ce que] tu sais te recharger;
<qfineandyou> : (ça va | je vais | tout va) (bien | pas mal) [merci] [et toi [comment ça va]];
<qgoodafternoon> : bon après-midi;
<qgoodevening> : bonsoir | bonne soirée;
<qgoodnight> : bonne nuit;
<qgoodday> : bonne journée;
<qgoodbye> : au revoir | à bientôt;
<qweathernice>:Il fait beau aujourd'hui;
<qhowarefriends>:Comment (vont mes amis | va <relative>);
<qnotwell>:Je ne suis pas très en forme [ce matin];
<qvisit>:[Cet après-midi | aujourd'hui | tout à l'heure] je vais voir <relative>;
<qsleepwell>:J'ai bien dormi [cette nuit];
<qpain>:J'ai mal (à la|à l'|au) (cheville | bras | poignet | pied | main | ventre | dent) [depuis (hier soir | ce matin)];
<qweathernotnice>:Il ne fait pas très beau aujourd'hui;
<qsickfriend>:<relative> est malade;
<qsunnyday>:Que puis-je faire avec ce beau soleil;
<qrainyday>:Il pleut et je m'ennuie;
<qmissfamily>:<relative> me manque;
<qfeelalone>:Je me sens seul;
<qwhattodo>:Qu'est ce que je peux faire aujourd'hui;
<qgrumpyfriend>:[(Je crois|j'ai l'impression) que] <relative> me fait la tête;
<qcontest>:Il y a concours de <game> [demain] [au club des anciens];
<qgoingtocook>:Je vais aller cuisiner [viens avec moi];
<qloosingmemory>:[Je (vieillis | deviens (vieux|vieille))] je perds la mémoire;
<qforgetmedecine>:J'oublie toujours de prendre mes médicaments;
<qsawsomeone>:J'ai vu <relative> tout à l'heure;
<qhadawalk>:Nous [nous] sommes (allés | promenés) au parc;
<qaremedoctaken>:(Ai-je pris | [est-ce que] j'ai pris) (les | mes) médicaments [aujourd'hui];
<qhereissone>:Voici <relative>;
<qlostglasses>: (Je ne trouve plus | j'ai perdu | je ne sais plus où j'ai mis) mes lunettes;
<qloststhing>:(Je ne trouve plus | j'ai perdu | je ne sais plus où (j'ai mis | sont | est) | (peux-tu | pourrais-tu | [est-ce que] tu peux) m'aider à retrouver) (mes clés | (ma | la) télécommande | mes aiguilles [à tricoter] | mon livre);
<qdentistappointment>:J'ai rendez-vous chez le dentiste;
<qmedicalappointmenteye>:J'ai rendez-vous chez l'ophtamologue;
<qfell>:Je suis tombée [j'ai mal];
<qmedicalappointment>: (J'ai rendez-vous | Il ne faut pas que j'oublie d'aller | il faut que j'aille) chez le (médecin | docteur | cardiologue) [demain];
<qsomeonedied>:(monsieur | madame) est décédé;
<qmybirthday>: [aujourd'hui] C'est mon anniversaire [aujourd'hui];
<qplaygame>:[Est-ce que] tu veux jouer <game>;
<qactivity>:Quelle activité me proposerais-tu;
<qlostgame>:J'ai [encore] perdu <game>;
<qcanplaymusic>:Sais-tu jouer de la musique;
<qfavoritebook>:Quel est (ton (film | livre) | ta pièce de théâtre) préféré;
<qwhatisontv>:Qu'y a-t-il (au cinéma  à la télé ) [ en ce moment | ce soir];
<qdanceshow>:[Ce soir] je vais voir un spectacle [de danse];
<qstory>:[Est-ce que] tu (peux | pourrais) me (lire un livre | raconter (une histoire | un poème));
<qlike>:(J'aime | je n'aime pas) (la musique classique | les romans [à l'eau de rose] | les western);
<qcookwithtomatoe>:Tu sais quoi faire avec des tomates;
<qsharefood>:J'ai envie de partager (une tarte | un gâteau | une salade | un repas);
<qseathesee>:J'ai jamais vu la mer et toi;
<qtravel>:Tu pars avec moi en voyage;
<qokaybuddy>:okay buddy;
<qokaygoogle>:okay google;
<qheyalexa>:hey alexa;
<relative> : (un | mon | mes) (amie | fils | frère) | (une | ma | mes) (fille| soeur);
<game> : [aux | à la] (bridge | échecs | dames | scrabble | pétanque | belote | cartes);

<qthankyou> : merci [buddy];
