#BNF+EMV2.1;
!grammar companion_questions_nl;

!start <qhello>;
!start <qhappy>;
!start <qwtcanyoudo>;
!start <qwhoareyou>;
!start <qname>;
!start <qhowareyou>;
!start <qcook>;
!start <qhoover>;
!start <qcoffee>;
!start <qeat>;
!start <qgender>;
!start <qrobot>;
!start <qkissyou>;
!start <qheight>;
!start <qweight>;
!start <qsize>;
!start <qautonomy>;
!start <qchargingtime>;
!start <qchargingmod>;
!start <qfineandyou>;
!start <qgoodafternoon>;
!start <qgoodevening>;
!start <qgoodnight>;
!start <qgoodday>;
!start <qgoodbye>;
!start <qfavoritemusic>;
!start <qfavoritemovie>;

!start <qweathernice>;
!start <qhowarefriends>;
!start <qnotwell>;
!start <qvisit>;
!start <qsleepwell>;
!start <qpain>;
!start <qweathernotnice>;
!start <qsickfriend>;
!start <qsunnyday>;
!start <qrainyday>;
!start <qmissfamily>;
!start <qfeelalone>;
!start <qwhattodo>;
!start <qgrumpyfriend>;
!start <qcontest>;
!start <qgoingtocook>;
!start <qloosingmemory>;
!start <qforgetmedecine>;
!start <qsawsomeone>;
!start <qhadawalk>;
!start <qaremedoctaken>;
!start <qhereissone>;
!start <qlostglasses>;
!start <qloststhing>;
!start <qdentistappointment>;
!start <qmedicalappointmenteye>;
!start <qfell>;
!start <qmedicalappointment>;
!start <qsomeonedied>;
!start <qmybirthday>;
!start <qplaygame>;
!start <qactivity>;
!start <qlostgame>;
!start <qcanplaymusic>;
!start <qfavoritebook>;
!start <qwhatisontv>;
!start <qdanceshow>;
!start <qstory>;
!start <qlike>;
!start <qcookwithtomatoe>;
!start <qsharefood>;
!start <qseathesee>;
!start <qtravel>;
!start <qwhathappen>;
!start <qthinkme>;
!start <qthinstoimprove>;
!start <qsayhappy>;
!start <qwhatdotoday>;
!start <qgod>;
!start <qwhatdogood>;
!start <qthanks>;
!start <qzeeland>;
!start <qproverb>;
!start <qsongs>;
!start <qquiznl>;
!start <qdialect>;
!start <qgoodmorning>;
!start <qyouare>;
!start <qcomehome>;

<qhello> : (hallo | hoi) [buddy];
<qhappy> : (je bent | ben je) blij om (bij ons | hier | hier bij ons | bij ons hier) te zijn;
<qwtcanyoudo> : wat kan je doen | (vertel (ons | me) | kun je (ons | me) vertellen) wat je kunt doen;
<qwhoareyou> : wie ben jij;
<qname> : wat is [je | jouw] naam | hoe heet [je | jij];
<qhowareyou> : hoe gaat het [met je];
<qcook> : kun [je | jij] koken | ben [je | jij] een goede kok;
<qhoover> : kun [je | jij] (schoonmaken | stofzuigen);
<qcoffee> : [kun [je | jij]] [een kop | een kopje] koffie zetten | koffie maken;
<qeat> : wat eet [je | jij] | heb [je | jij] [wel eens] honger | [wat] wil [je | jij] [wat | iets] eten;
<qgender> : ben jij (een jongen | een jongetje | mannelijk | [een] man | [een] hij | [een] meisje | vrouwelijk | [een] vrouw | [een] zij) [of een (jongen | meisje | vrouw | man)];
<qrobot> : (ben [jij | je] | [jij | je] bent) [dus] [een] robot;
<qkissyou> : [kan ik | mag ik | zal ik] ([een] kus | [een] zoen) geven;
<qheight> : hoe (groot | lang | hoog) ben [je | jij] | wat is [jouw | je] (hoogte | lengte);
<qweight> : hoe zwaar [ben] [je | jij] | [wat is] [je | jouw] gewicht;
<qsize> : hoe (groot | hoog) ben [je | jij] | [wat zijn] [je | jouw] (afmeting | afmetingen);
<qautonomy> : hoe lang (gaat | kan) [de | je | jouw] batterij [mee] | [hoe snel | wanneer] is (je | de) batterij leeg;
<qchargingtime> : hoe lang [duurt het om] (op te laden | opladen);
<qchargingmod> : hoe [werkt | gaat] [het] opladen [van (de | je | jouw) batterij];
<qfineandyou> : [met mij] [gaat het | is het] [heel | erg] (goed | prima) [en (met jou | hoe is [het] met jou | hoe gaat [het] met jou)] ;
<qgoodafternoon> : goede middag | goeie middag | goedemiddag | goeiemiddag | middag;
<qgoodevening> : goedenavond | goeienavond;
<qgoodnight> : goede nacht | fijne avond | slaap lekker | welterusten;
<qgoodday> : [jij ook] [een] (fijne dag | mooie dag);
<qgoodbye> : tot ziens | dahag;
<qfavoritemusic> : wat is (jouw | je) (favoriete muziek | lievelingsmuziek | mooiste muziek | beste muziek);
<qfavoritemovie> : wat is (jouw | je) (favoriete film | lievelingsfilm | mooiste film | beste film);

<qweathernice>:het (wordt | is) (mooi | goed | warm) weer [vandaag];
<qhowarefriends>:Hoe gaat [het met] mijn vrienden; 
<qnotwell>:ik ben niet [erg] fit [vandaag | op dit moment];
<qvisit>:[vanmiddag | vandaag | straks | later] ga ik naar <relative>;  
<qsleepwell>:ik heb [vannacht | deze nacht] (goed | lekker) geslapen [vannacht | deze nacht];
<qpain>: ik heb pijn [in (mijn | de | het)] (enkel | enkels | arm | armen | hand | handen | voet | voeten | heup | heupen | rug | tand | tanden | kies | kiezen) [sinds (vanochtend | gisteren | vandaag | vannacht)];
<qweathernotnice>: het (is | wordt) [vandaag] (geen mooi | slecht | minder) weer [vandaag];
<qsickfriend>:<relative> is ziek;
<qsunnyday>:wat een mooie dag; 
<qrainyday>: het regent [en ik verveel me] | het is aan het regenen | wat een vies weer [buiten];
<qmissfamily>: ik mis <relative> [heel erg];
<qfeelalone>: ik (voel me | ben) [zo | heel | erg] (alleen | eenzaam);
<qwhattodo>: wat (zal | kan | zou) ik [vandaag] [eens] [gaan] doen [vandaag];
<qgrumpyfriend>:[ik denk dat] <relative> niet in een goed humeur is;  
<qcontest>:er is een wedstrijd [vandaag | morgen];
<qgoingtocook>: ik (ga | moet) koken [kom je mee | kom maar met me mee | kom maar mee];
<qloosingmemory>: [ik word oud | wat word ik oud | wat word ik weer oud] [ik ben mijn] geheugen kwijt | [mijn] geheugen [is een] zeef;
<qforgetmedecine>:ik vergeet altijd [mijn | me | die | de] (medicijnen | medicijn | pillen | pil | drankje | spuitje | insuline) [in te nemen];
<qsawsomeone>:Ik heb <relative> [net | zojuist] gezien;
<qhadawalk>:we zijn [wezen | gaan] wandelen in het park | we hebben een wandeling gemaakt | we gingen wandelen | we gingen een ommetje lopen;
<qaremedoctaken>: Heb ik [mijn | de | die | mun] (medicijn | medicijnen | pillen | pilletjes | drankje | spuitje | insuline);
<qhereissone>:(hier is | daar is) <relative>;
<qlostglasses>: ik [ben | heb] mijn bril [verloren |kwijt] | ik kan [mijn | mun] bril (niet | nergens) vinden | ik weet niet waar ik mijn bril heb neergelegd | ik weet niet waar mijn bril is | waar is mijn bril;
<qloststhing>: Ik ben [mijn] (mobiel | telefoon | boek | breinaalden | breiwerk | puzzelboekje | sleutels) kwijt. | wil je [helpen] zoeken [naar mijn] (mobiel | telefoon | boek | breinaalden | breiwerk | puzzelboekje | sleutels);
<qdentistappointment>:[ik heb een] afspraak [met | bij] [de] tandarts | ik moet naar [de] tandarts;
<qmedicalappointmenteye>:[ik heb een] afspraak [met | bij] [de] oogarts;
<qfell>:ik ben gevallen [ik heb pijn | het doet pijn];
<qmedicalappointment>: ik heb een afspraak | [ik moet] niet vergeten dat ik [een afspraak heb] met [de] (arts | huisarts | dokter | huisdokter | fysio | cardioloog | specialist) [vandaag | morgen] | Ik moet [vandaag | morgen] naar [de] (arts | huisarts | dokter | huisdokter | fysio | cardioloog | specialist);
<qsomeonedied>:(meneer | mevrouw) is overleden;
<qmybirthday>: [vandaag] ben ik jarig | is mijn verjaardag | vier ik mijn verjaardag | ik voer mijn verjaardag vandaag | ik ben jarig vandaag | ik ben vandaag jarig;
<qplaygame>: [wil je | kun je | zullen we] een spelletje <game> spelen;
<qactivity>:heb je een idee wat ik kan doen | wat is je voorstel om te doen | wat zal ik gaan doen | wat (kan | zal) ik [eens] doen;
<qlostgame>:ik heb [alweer | weer] verloren met <game>;
<qcanplaymusic>: (kun | wil) [jij | je] muziek (maken | spelen | afspelen);
<qfavoritebook>:wat is (jouw | je) (favoriete boek | lievelingsboek | mooiste boek | beste boek);
<qwhatisontv>: wat [is er] (op dit moment | vannavond) op (tv | televisie);
<qdanceshow>:[vanavond] ga ik naar (een dansvoorstelling | een dansuitvoering);
<qstory>: [wil je |kun je | kan je] (een boek voorlezen | voorlezen | een verhaal vertellen | over vroeger vertellen | een gedicht voordragen);
<qlike>:(ik houd | ik houd niet) (van klassieke muziek | westerns | zoete romans);
<qcookwithtomatoe>:[Je weet wat] [je met] tomaten [moet] doen;
<qsharefood>: ik wil [wel] (een taart | een cake | een salade | een maaltijd) delen | zullen we (een taart | een cake | een salade | een maaltijd) delen | wil je ook [wat | een stukje | een beetje | wat eten];
<qseathesee>: ik wil met jou naar [het strand | zee | de zee | de boelevaar];  
<qtravel>:Ga je [ook] mee [op | met | naar] vakantie;
<relative> : (1 | mijn) (vriend | broer | zus);  
<game> : scrabble | domino | kwartet | kaart | yahtzee ;  

<qwhathappen>: wat gebeurde [er] vandaag;
<qthinkme>: Wat denk je van mij;
<qthinstoimprove>: Wat kan ik doen om [beter te worden | te verbeteren];
<qsayhappy>: (zeg eens | vertelen me) [eens] [iets] (moois | blijs | fijns);
<qwhatdotoday>: wat ga je vandaag doen;
<qgod>: God exists;
<qwhatdogood>: What could I do good;
<qthanks> : (dankjewel | dank je [wel] | [veel | hartelijk] bedankt | (veel | hartelijk) dank ) [buddy];
<qzeeland> : (vertel me iets over | informatie over) zeeland | [wat weet je] over zeeland;
<qproverb> : [weet je een] (spreekwoord | gezegde | uitdrukking);
<qsongs> : [kun je | wil je een] lied [met (me | mij)] zingen;
<qquiznl> : ik wil een quiz (doen | spelen) | volgende [quiz] vraag;
<qdialect> : [kun je] (ons dialect | de zeeuwse taal) (spreken | zeggen | praten);
<qgoodmorning> : goedemorgen | goeiemorgen;
<qyouare> : (jij bent | wat ben jij) (mooi | leuk | lief | schattig | grappig | aardig) ;
<qcomehome> : [kom je] [bij mij] logeren | [kom je] [bij mij] op visite;
