#BNF+EMV2.1;
!grammar companion_questions_nl;

!start <qhello>;
!start <qhappy>;
!start <qwtcanyoudo>;
!start <qwhoareyou>;
!start <qname>;
!start <qhowareyou>;
!start <qcook>;
!start <qhoover>;
!start <qcoffee>;
!start <qeat>;
!start <qgender>;
!start <qrobot>;
!start <qkissyou>;
!start <qheight>;
!start <qweight>;
!start <qsize>;
!start <qautonomy>;
!start <qchargingtime>;
!start <qchargingmod>;
!start <qfineandyou>;
!start <qgoodafternoon>;
!start <qgoodevening>;
!start <qgoodnight>;
!start <qgoodday>;
!start <qgoodbye>;

<qhello> : hallo [buddy];
<qhappy> : (je bent | ben je) blij om (bij ons | hier) te zijn;
<qwtcanyoudo> : wat kan je doen | (vertel (ons | me) | kun je (ons | me) vertellen) wat je kunt doen;
<qwhoareyou> : wie ben jij;
<qname> : (what is | what's) your name | do you have a name;
<qhowareyou> : hoe gaat het [met je];
<qcook> : ((can | do) you | do you know how to) cook | are you a good cook;
<qhoover> : can you (hoover | clean the house);
<qcoffee> : [can you] (make | get) [me] [a] coffee;
<qeat> : what do you eat  | are you hungry  | do you want to eat  | do you wanna eat;
<qgender> : are you (a boy  | a he  | a girl  | a she);
<qrobot> : (are you| you are) a robot [then];
<qkissyou> : can I (kiss you | give you a kiss);
<qheight> : how tall are you | (what is | what's) your height;
<qweight> : how much do you weigh | (what is | what's) your weight;
<qsize> : what are your dimensions | what is your size | what size are you;
<qautonomy> : (what is | what's)  your (battery life | autonomy) | how long (last your battery | does your batterie last);
<qchargingtime> : how long [does it take] to recharge your battery;
<qchargingmod> : how do you (fill your battery up | fill up your battery | recharge [yourself]);
<qfineandyou> : [I'm] (fine | [very] good) [and you | what about you];
<qgoodafternoon> : good afternoon;
<qgoodevening> : good evening;
<qgoodnight> : good night;
<qgoodday> : have a good day;
<qgoodbye> : tot ziens;