#BNF+EMV2.1;
!grammar companion_commands_nl;

!start <battery>;
!start <canmove>;
!start <dance>;
!start <date>;
!start <demoshort>;
!start <dontmove>;
!start <dosomething>;
!start <followme>;
!start <gallery>;
!start <headdown>;
!start <headleft>;
!start <headright>;
!start <headup>;
!start <hour>;
!start <ihateyou>;
!start <iloveyou>;
!start <joke>;
!start <kissme>;
!start <mood>;
!start <movebackward>;
!start <moveforward>;
!start <moveleft>;
!start <moveright>;
!start <nap>;
!start <photo>;
!start <registerreminder>;
!start <repeat>;
!start <tellsomething>;
!start <volume>;
!start <volumedown>;
!start <volumeup>;
!start <wander>;
!start <sick>;
!start <sad>;
!start <lovely>;
!start <happy>;
!start <tired>;
!start <angry>;
!start <grumpy>;
!start <scared>;
!start <operation>;
!start <operationagain>;
!start <accraactivity>;
!start <accraalarm>;
!start <quit>;
!import <numbers#nb>;

<asklaunch> : [<canyou>] (open | launch | play) [[the] application];
<asktell> : [<canyou>] (tell | find | give) [me | us] | I want to hear;
<canyou> : (can | could) you;


<battery> : [<asktell> | what is | what's] [your] battery [level];
<canmove> : je kunt bewegen;
<dance> : Dansen;
<date> : wat is de datum;
<demoshort> : Stel jezelf snel | snel voor wat je kunt doen | wat je snel kunt doen | wat je binnenkort kunt doen | Pronk met kort | korte demo;
<dontmove> : niet bewegen;
<dosomething> : (do | show me) something;
<followme> : track me | follow [me] | come with me;
<gallery> : laat me mijn foto's zien;
<headdown> : ([move (the | your)] head | look) [<rotationangle>] down;
<headleft> : (turn (the | your) head | look) [<rotationangle>] [(on | to) the] left;
<headright> : (turn (the | your) head | look) [<rotationangle>] [(on | to) the] right;
<headup> : ([move (the | your)] head | look) [<rotationangle>] up | lift up your head;
<hour> : what time is it | give [me | us] the time | what is the time;
<ihateyou> : I (hate | despite | don't like)  you | you (sucks | are (a loser | [so] bad | mean | stupid | a stupid robot)) | you are not funny;
<iloveyou> : I love you | I really like you |  I like playing with you | [you are a] good boy | you are (nice | smart);
<joke> : [<asktell>] (a joke | a funny story | something funny);
<kissme> : kiss me |  I want a kiss | give me a kiss;
<mood> : [what is | what's] [your] mood;
<movebackward> : ga achteruit;
<moveforward> : ga vooruit;
<moveleft> : draai naar links;
<moveright> : draai naar rechts;
<nap> : (take a nap | go to sleep) [during <delai>];
<photo> : [[can you | let's] take] (a photo | a picture | pictures | photos);
<registerreminder> : [[Can you] (add | save | put | register)]  [a] reminder;
<repeat> : I didn't hear you [well] | I didn't understand | can you (repeat | say [it] again) [please] | [sorry] what did you say | repeat;
<tellsomething> : tell me something | [tell me a] fun fact;
<volume> : Wat is het volume | geef me het volume | volumeniveau;
<volumeup> : volume omhoog | geluid omhoog;
<volumedown> : volume lager | geluid zachter;
<wander> : rondlopen | weggaan | wandelen | een ritje maken | een wandeling maken | een wandeling maken | rondwandelen | ronddwalen;
<show> : show [me | us] when you are | be;
<sick> : <show> sick;
<sad> : <show> sad;
<lovely> : <show> (lovely | in love);
<happy> : <show> (happy | joy | joyful);
<tired> : <show> tired;
<angry> : <show> excited;
<grumpy> : <show> grumpy;
<scared> : <show> scared;
<delai> : <numbers#nb> (seconds | minutes | hours);
<rotationangle> : <numbers#nb> degrees;
<operation> : [(how much are | what is)] <numbers#nb> (plus | minus | divided by | multiplied by | times) <numbers#nb>;
<operationagain> :  (plus | minus | divided by | multiplied by | times) <numbers#nb>;
<accraactivity> : [<canyou> | (I | we) (want to | would like [you] to) | can I] (launch | start | do | make) (an exercice | an activity | a session);
<accraalarm> : Call for help | Alert (an helper | someone) | I'm not really well | I have a problem;
<quit> : Stop | houd op |  stop daarmee;