#BNF+EMV2.1;
!grammar companion_questions_it;
!start <qhello>;
!start <qhappy>;
!start <qwtcanyoudo>;
!start <qwhoareyou>;
!start <qname>;
!start <qchangename>;
!start <qhowareyou>;
!start <qcook>;
!start <qhoover>;
!start <qcoffee>;
!start <qlanguage>;
!start <qeat>;
!start <qage>;
!start <qfather>;
!start <qparents>;
!start <qwhomadeyou>;
!start <qgender>;
!start <qrobot>;
!start <qmimicdog>;
!start <qmimiccat>;
!start <qsiblings>;
!start <qkissyou>;
!start <qknowroboticrules>;
!start <qroboticrules>;
!start <qfavoritecolor>;
!start <qfavoritemusic>;
!start <qfavoriteactor>;
!start <qfavoriteactress>;
!start <qfavoritemovie>;
!start <qfavoritegame>;
!start <qheight>;
!start <qweight>;
!start <qsize>;
!start <qautonomy>;
!start <qchargingtime>;
!start <qchargingmod>;
!start <qfineandyou>;
!start <qgoodafternoon>;
!start <qgoodevening>;
!start <qgoodnight>;
!start <qgoodday>;
!start <qgoodbye>;
!start <qweathernice>;
!start <qhowarefriends>;
!start <qnotwell>;
!start <qvisit>;
!start <qsleepwell>;
!start <qpain>;
!start <qweathernotnice>;
!start <qsickfriend>;
!start <qsunnyday>;
!start <qrainyday>;
!start <qmissfamily>;
!start <qfeelalone>;
!start <qwhattodo>;
!start <qgrumpyfriend>;
!start <qcontest>;
!start <qgoingtocook>;
!start <qloosingmemory>;
!start <qforgetmedecine>;
!start <qsawsomeone>;
!start <qhadawalk>;
!start <qaremedoctaken>;
!start <qhereissone>;
!start <qlostglasses>;
!start <qloststhing>;
!start <qdentistappointment>;
!start <qmedicalappointmenteye>;
!start <qfell>;
!start <qmedicalappointment>;
!start <qsomeonedied>;
!start <qmybirthday>;
!start <qplaygame>;
!start <qactivity>;
!start <qlostgame>;
!start <qcanplaymusic>;
!start <qfavoritebook>;
!start <qwhatisontv>;
!start <qdanceshow>;
!start <qstory>;
!start <qlike>;
!start <qcookwithtomatoe>;
!start <qsharefood>;
!start <qseathesee>;
!start <qtravel>;
!start <qwhathappen>;
!start <qthinkme>;
!start <qthinstoimprove>;
!start <qsayhappy>;
!start <qwhatdotoday>;
!start <qgod>;
!start <qwhatdogood>;

<qhello> :ciao [buddy];
<qhappy> : ([sei] contento | felice) [di essere (con noi | qui)];
<qwtcanyoudo> :che sai fare  | ((dimmi | dicci) | (potresti | puoi)(spiegarmi | spiegarci)) cosa sai fare. | cos'è che sai fare;
<qwhoareyou> : [tu] chi sei;
<qname> : cometi chiami | qual è il tuo nome;
<qchangename> : (posso| possiamo | si può) cambiareil tuo (cognome | nome);
<qhowareyou> : come (stai | va) | stai bene;
<qcook> :sai (cucinare | fare da  mangiare) | cucini;
<qhoover> : (passi | sai passare) l'aspirapolvere;
<qcoffee> : fai il caffè | sai fare il caffè | fammi un caffè;
<qlanguage> :che lingua parli;
<qeat> :cosa mangi | hai fame | vuoi mangiare;
<qage> :quanti anni hai | (quando | che giorno | in quale anno) sei nato | quand'è il tuo compleanno;
<qfather> : chi è tuo padre;
<qparents> : (chi sono i tuoi | hai dei) genitori | che origini hai;
<qwhomadeyou> :chi ti ha (costruito| fabbricato);
<qgender> :sei (un uomo | un ragazzo | una donna | una ragazza);
<qrobot> : sei un robot [allora];
<qmimicdog> : imitail cane;
<qmimiccat> : imita il gatto;
<qsiblings> :hai fratelli e sorelle;
<qkissyou> :posso darti un bacio | posso baciarti;
<qknowroboticrules> :a quali regole obbediscono i robot | (tu (rispetti | conosci) | sai | chi ha inventato) le (leggi | regole) (della robotica | dei robot);
<qroboticrules> :quali sono le (leggi | regole) della robotica| a quali regole obbediscono i robot;
<qfavoritecolor> : qual è il tuo colore preferito;
<qfavoritemusic> :qual è la tua musica preferita;
<qfavoriteactor> :qual è il tuo attore preferito;
<qfavoriteactress> :qual è la tua attrice preferita;
<qfavoritemovie> :qual è il tuo film preferito;
<qfavoritegame> :qual è il tuo gioco preferito;
<qheight> :quanto sei alto | quanto misuri | che altezza hai;
<qweight> :quanto pesi | qual è il tuo peso;
<qsize> :che dimensioni hai;
<qautonomy> :che autonomia hai | quanto durala tua batteria | qual è la durata della tua batteria | quanto tempo durala tua batteria;
<qchargingtime> :quanto ci impieghi a ricaricarti | che tempi di ricarica hai | in quanto tempo ti ricarichi | quanto tempo ti ci vuole per ricaricarti;
<qchargingmod> : come ti (ricarichi | carichi) | ti sai ricaricare;
<qfineandyou> : (io sto | tutto va) (bene | niente male) [grazie] [e tu [come stai]];
<qgoodafternoon> :buon pomeriggio;
<qgoodevening> :buonasera | buona serata;
<qgoodnight> :buona notte;
<qgoodday> :buona giornata;
<qgoodbye> :arrivederci | a presto;

<qweathernice>:È una bella giornata oggi;
<qhowarefriends>:Come (state amici | va <relative>);
<qnotwell>: Non sono molto in forma [stamattina];
<qvisit>:[oggi pomeriggio | oggi | presto] incontro<relative>;
<qsleepwell>: Ho dormito bene [stanotte];
<qpain>:Mi fa male (la|l'|il) (caviglia | braccio | polso | piede | mano | pancia | dente) [da (ieri sera | stamattina)];
<qweathernotnice>:Non è una bella giornata oggi;
<qsickfriend>:<relative>sta male;
<qsunnyday>:Che posso fare in questa giornata di sole;
<qrainyday>:Piove e mi annoio;
<qmissfamily>:<relative>mi manchi;
<qfeelalone>:Mi sento solo;
<qwhattodo>:Che posso fare oggi;
<qgrumpyfriend>:[(Credo|Ho l'impressione) di] <relative> avere mal di testa;
<qcontest>:C'è un campionato di <game> [domani] [al circolo degli anziani];
<qgoingtocook>:Vado a cucinare [vieni con me];
<qloosingmemory>:[Sto (Invecchiando | diventando (vecchio | vecchia))] sto perdendo la memoria;
<qforgetmedecine>:Mi dimentico sempre di prendere le medicine;
<qsawsomeone>:Ho visto <relative> prima;
<qhadawalk>:Noi [nous] (siamo andati | abbiamo fatto una passeggiata) al parco;
<qaremedoctaken>:Ho preso (le | le mie) medicine [oggi];
<qhereissone>: Ecco<relative>;
<qlostglasses>: (Non trovo | Ho perso | non ricordo dove ho messo) i miei occhiali;
<qloststhing>:( Non trovo | Ho perso | non ricordo dove (ho messo | sono | è) | (puoi | potresti) aiutarmi a ritrovare) (le mie chiavi | (il mio | il) telecomando | i miei ferri da maglia | il mio libro);
<qdentistappointment>:Ho appuntamento dal dentista;
<qmedicalappointmenteye>:Ho appuntamento dall'oculista;
<qfell>:Sono caduto [mi fa male];
<qmedicalappointment>: (Ho appuntamento | Non devo dimenticarmi di andare | devo andare) dal (medico | dottore | cardiologo) [domani];
<qsomeonedied>:(il signore| la signora) è (deceduto | deceduta);
<qmybirthday>: [oggi] è il mio compleanno [aujourd'hui];
<qplaygame>:Vuoi giocare <game>;
<qactivity>:Che attività mi proporrai;
<qlostgame>:Ho perso [di nuovo] a<game>;
<qcanplaymusic>:Sai suonare qualche strumento;
<qfavoritebook>:Qual è il tuo (film | libro | spettacolo teatrale) preferito;
<qwhatisontv>:Cosa danno (al cinema | in tv) [ora | stasera];
<qdanceshow>:[Stasera] vedrò uno spettacolo [di danza];
<qstory>:(Puoi | Potresti) (leggermi (un libro | una poesia) raccontarmi una storia);
<qlike>:(Mi piace | non mi piace) (la musica classica | i romanzi [rosa] | i western);
<qcookwithtomatoe>:Sai cosa fare con dei pomodori;
<qsharefood>:Ho voglia di condividere (una crostata | una torta | un'insalata | uno spuntino);
<qseathesee>:Non ho mai visto il mare e tu;
<qtravel>:Partiamo insieme;
<relative> :(un | mio | i miei) (amico | figlio | fratelli) | (una | mia | le mie) (figlia| sorelle);
<game> :a ( bridge | scacchi | dama | scarabeo | bocce | pinnacolo | carte);
<qwhathappen> :Cosa è successo oggi;
<qthinkme> :Cosa pensi di me;
<qthinstoimprove> :Cosa potrei fare per (migliorare | per stare meglio);
<qsayhappy> :Mi (dici| sai dire) qualcosa di (bello|felice);
<qwhatdotoday> :Cosa faresti oggi;
<qgod> :Esiste Dio;
<qwhatdogood> :Cosa potrei fare di buono;








