#BNF+EMV2.1;
!grammar companion_questions_en;
!start <qhello>;
!start <qhappy>;
!start <qwtcanyoudo>;
!start <qwhoareyou>;
!start <qname>;
!start <qchangename>;
!start <qhowareyou>;
!start <qcook>;
!start <qhoover>;
!start <qcoffee>;
!start <qlanguage>;
!start <qeat>;
!start <qage>;
!start <qfather>;
!start <qparents>;
!start <qwhomadeyou>;
!start <qgender>;
!start <qrobot>;
!start <qmimicdog>;
!start <qmimiccat>;
!start <qsiblings>;
!start <qkissyou>;
!start <qknowroboticrules>;
!start <qroboticrules>;
!start <qfavoritecolor>;
!start <qfavoritemusic>;
!start <qfavoriteactor>;
!start <qfavoriteactress>;
!start <qfavoritemovie>;
!start <qfavoritegame>;
!start <qheight>;
!start <qweight>;
!start <qsize>;
!start <qautonomy>;
!start <qchargingtime>;
!start <qchargingmod>;
!start <qfineandyou>;
!start <qgoodafternoon>;
!start <qgoodevening>;
!start <qgoodnight>;
!start <qgoodday>;
!start <qgoodbye>;
//!start <qwherearewe>;
//!start <qwhatareyoudoing>;
//!start <qfriends>;
!start <qavatarion>;
!start <qswizz>;
!start <qwtcanyoudoelderly>;
!start <qwtcanyoudochildren>;
!start <qwhyinvest>;
!start <qokaybuddy>;
!start <qokaygoogle>;
!start <qheyalexa>;

<qhello> : (hello | hi | hey) [buddy];
<qhappy> : are you happy [to be (here | with us)];
<qwtcanyoudo> : what can you do [for (me | us)] | tell (me | us) what you can do;
<qwhoareyou> : who are you;
<qname> : (what is | what's) your name | do you have a name;
<qchangename> : (can | could) I (change your name | call you something else);
<qhowareyou> : how are you [doing] | what's up | (how's | how is) it going | how do you do;
<qcook> : ((can | do) you | do you know how to) cook | are you a good cook;
<qhoover> : can you (hoover | clean the house);
<qcoffee> : [can you] (make | get) [me] [a] coffee;
<qlanguage> : what (languages | language) (can | do) you speak  ;
<qeat> : what do you eat  | are you hungry  | do you want to eat  | do you wanna eat;
<qage> : how old are you  | when is your birthday  | (on which day | when) were you born;
<qfather> : (who is | who's) your (father | dad | daddy);
<qparents> : (who are | do you have) parents | where do you come from;
<qwhomadeyou> : who (conceived | made) you ;
<qgender> : are you (a boy  | a he  | a girl  | a she);
<qrobot> : (are you| you are) a robot [then];
<qmimicdog> : (mimic | imitate) (a | the) dog;
<qmimiccat> : (mimic | imitate) (a | the) cat;
<qsiblings> : do you have (brothers | a brother | sisters | a sister | siblings | brothers and sisters);
<qkissyou> : can I (kiss you | give you a kiss);
<qknowroboticrules> : (do you follow | do you respect) [the] robotics laws | do you know isaac asimov;
<qroboticrules> : what are the robotics laws | do you know robotics laws;
<qfavoritecolor> : (what is | what's) your favorite color;
<qfavoritemusic> : (what is | what's) your favorite music | what do you like to listen  | what do you listen to;
<qfavoriteactor> : (what is | what's) your favorite actor;
<qfavoriteactress> : (what is | what's) your favorite actress;
<qfavoritemovie> : (what is | what's) your favorite movie | (what | which) movie do you like;
<qfavoritegame> : (what is | what's) your favorite game | do you like playing;
<qheight> : how tall are you | (what is | what's) your height;
<qweight> : how much do you weigh | (what is | what's) your weight;
<qsize> : what are your dimensions | what is your size | what size are you;
<qautonomy> : (what is | what's)  your (battery life | autonomy) | how long (last your battery | does your batterie last);
<qchargingtime> : how long [does it take] to recharge your battery;
<qchargingmod> : how do you (fill your battery up | fill up your battery | recharge [yourself]);
<qfineandyou> : [I'm] (fine | [very] good) [and you | what about you];
<qgoodafternoon> : good afternoon;
<qgoodevening> : good evening;
<qgoodnight> : good night;
<qgoodday> : have a good day;
<qgoodbye> : goodbye | see you soon;
//<qwherearewe> : where are we;
//<qwhatareyoudoing> : what are you doing here;
//<qfriends> : (who are your | do you have [any]) friends;
<qavatarion> : [tell me] (who is | do you know) Avatarion;
<qswizz> : (what do you like about | do you like) Switzerland;
<qwtcanyoudoelderly> : what can you do for elder care | could you help senior | are you a good companion for (elders | elderly);
<qwtcanyoudochildren> : (what can you do for | could you help | are you a good companion for) (children | kids);
<qwhyinvest> : why invest in (Buddy | Blue Frog Robotics);
<qokaybuddy>:okay buddy;
<qokaygoogle>:okay google;
<qheyalexa>:hey alexa;