#BNF+EMV2.0;
!grammar duration_fr;
!import <numbers#nb>;

!export <duration_years>;
!export <duration_months>;
!export <duration_weeks>;
!export <duration_days>;
!export <duration_hours>;
!export <duration_minutes>;
!export <duration_hoursandminutes>;

<duration_years> : <nb_minutes> (an[s] | année[s]);
<duration_months> : <numbers#nb> mois[s];
<duration_weeks> : <nb_minutes> semaine[s];
<duration_days> : <numbers#nb> jour[s];
<duration_hours> : <nb_minutes> heure[s];
<duration_minutes> : <nb_minutes> minute[s];
<duration_hoursandminutes> : <duration_hours> <andminutes>;

<firstthirtyminutes> : 1 | une | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | vingt-et-une | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29;
<nb_minutes> : <firstthirtyminutes> | 30 | 31 | trente-et-une | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | quarante-et-une | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | cinquante-et-une | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59;
<andminutes> : [et] <nb_minutes> [minute[s]] | moins <firstthirtyminutes> [minute[s]] | et demi | (et | moins le) quart;