#BNF+EMV2.1;
!grammar guardian_en;
!start <fixed>;
!start <mobile>;
!start <modifyparam>;
!start <start>;
!start <quit>;
<fixed> : don't move | (fixed | fix) [guard];
<mobile> : mobile [guard] | move;
<modifyparam> : [modify] parameters | parameter | configuration | parameterize | settings | set | setting;
<start> : start | launch | begin | watch | activate;
<quit> : quit | leave;
